Quantum Connector Update - 2025-05-20 22:15:33

diff --git a/.github/workflows/find-and-sign.yml b/.github/workflows/find-and-sign.yml
--- a/.github/workflows/find-and-sign.yml
+++ b/.github/workflows/find-and-sign.yml
@@ -1,12 +1,19 @@
 # @Author: Dr. Jeffrey Chijioke-Uche
 # @last update: 2025-03-01
 
-name: Find Only Latest Commit & Sign it with GPG
+name: Find Latest & Sign
 
 on:
   workflow_dispatch:
   push:
     branches: ["pypi"]
+  workflow_call:
+    secrets:
+      GPG_NAME_REAL: {required: true}
+      GPG_NAME_EMAIL: {required: true}
+      GPG_PRIVATE_KEY: {required: true}
+      GPG_PASSPHRASE: {required: true}
+      EXPECTED_GPG_KEY_ID: {required: true}
 
 permissions:
   contents: write
@@ -19,7 +26,7 @@ jobs:
       - name: ⬇️ Checkout code
         uses: actions/checkout@v4
         with:
-          fetch-depth: 2   
+          fetch-depth: 2
 
       - name: Set up Git user
         run: |
@@ -31,15 +38,14 @@ jobs:
           GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
           GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
         run: |
+          export GPG_TTY=$(tty)
           echo "${GPG_PASSPHRASE}" | \
           gpg --batch --yes --pinentry-mode loopback --passphrase-fd 0 --import <(echo "${GPG_PRIVATE_KEY}")
 
       - name: Find if latest commit is signed
         id: check_sig
         run: |
-          # Get latest commit hash
           LATEST_COMMIT=$(git rev-parse HEAD)
-          # Check if it's GPG signed
           if git log --format='%G?' -1 $LATEST_COMMIT | grep -q 'G'; then
             echo "✅Latest commit is already signed."
             echo "signed=yes" >> $GITHUB_OUTPUT
@@ -65,4 +71,5 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          git push --force-with-lease
+          git push --force-with-lease || { echo "❌ Push failed!"; exit 1; }
+
