Quantum Connector Update - 2025-05-21 14:54:56

diff --git a/.github/workflows/release-tag.yml b/.github/workflows/release-tag.yml
--- a/.github/workflows/release-tag.yml
+++ b/.github/workflows/release-tag.yml
@@ -219,7 +219,7 @@ jobs:
           done
 
       #=============================================================
-      - name: 🔍 Checking Release Tag Naming Violation
+      - name: 🔍 Pre - Checking Release Tag Naming Violation
         shell: bash
         run: |
           echo "🔎 Validating tag: ${{ github.ref_name }}"
@@ -291,4 +291,42 @@ jobs:
         env:
           GH_TOKEN: ${{ secrets.PAT_GITHUB }}
           GITHUB_REF_NAME: ${{ github.ref_name }}
-      # ================================
+      # =============================================================
+
+       #=============================================================
+      - name: 🔍 Post - Checking Release Tag Naming Violation
+        shell: bash
+        run: |
+          echo "🔎 Validating tag: ${{ github.ref_name }}"
+
+          TAG="${{ github.ref_name }}"
+          PROHIBITED_TAGS=(main stable pypi bug dev prod qa test lab)
+
+          for word in "${PROHIBITED_TAGS[@]}"; do
+            if [[ "$TAG" == *"$word"* ]]; then
+              echo "🚫 Tag name '$TAG' contains prohibited keyword: '$word'"
+              echo "🗑️ Deleting invalid tag (locally and remotely)..."
+
+              git tag -d "$TAG" || echo "⚠️ Local tag '$TAG' not found or already deleted."
+              git push origin :refs/tags/"$TAG" || echo "⚠️ Remote tag '$TAG' not found or already deleted."
+
+              echo "🧹 Tag '$TAG' deleted due to naming violation."
+              exit 0
+            fi
+          done
+
+          # Enforce semantic versioning: x.y.z or x.y.z-rc01
+          if [[ ! "$TAG" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]{2})?$ ]]; then
+            echo "🚫 Tag '$TAG' does not follow semantic version pattern like '2.2.6' or '2.1.5-rc01'"
+
+            git tag -d "$TAG" || echo "⚠️ Local tag '$TAG' not found or already deleted."
+            git push origin :refs/tags/"$TAG" || echo "⚠️ Remote tag '$TAG' not found or already deleted."
+
+            echo "🧹 Tag '$TAG' deleted due to naming pattern violation."
+            exit 0
+          fi
+
+          echo "✅ All Clear! Tag '$TAG' passed validation."
+        env:
+          GH_TOKEN: ${{ secrets.PAT_GITHUB }}
+          GITHUB_REF_NAME: ${{ github.ref_name }}
